apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "aksnettagtest1-51bf"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "aksnettagtest1-51bf"
    spec:
      containers:
        - name: "aksnettagtest1-51bf"
          image: "nodkubeacr.azurecr.io/aksnettagtest1"
          ports:
          - containerPort: 8080